#!/usr/bin/env perl

use strict;
use warnings;

my %data;
my $year = (localtime (time))[5] + 1900;

if (@ARGV &&
    ! -f $ARGV[0])
{
  $year = shift @ARGV;
}

while (my $line = <>)
{
  print $line;
  if ($line =~ /File does not exist: / &&
      $line !~ /favicon\.ico|robots\.txt/)
  {
    if ($line =~ / ${year} / ||
        $line =~ /\/${year}:/)
    {
      chomp $line;
      $line =~ s/, referer:.+//;
      my ($file) = $line =~ /File does not exist: (.+)/;
      $data{$file}++;
    }
  }
}

# Truncate anything with < 2 404s.
for (keys %data)
{
  delete $data{$_} if $data{$_} < 2;
}

print $year, "\n\n";
printf ("%6d %s\n", $data{$_}, $_) for sort {$data{$b} <=> $data{$a}}keys %data;
exit 0;

