#!/usr/bin/env perl

use strict;
use warnings;

my $counter = 0;
my $year = (localtime (time))[5] + 1900;

if (@ARGV &&
    ! -f $ARGV[0])
{
  $year = shift @ARGV;
}

while (my $line = <>)
{
  next if $line !~ /\/${year}/;
  next if $line !~ /GET \/latest/;
  next if $line !~ /" 200 /;

  $counter++;
}

print $year, "\n\n";
printf "%6d LATEST\n", $counter;
exit 0;

