#!/usr/bin/env perl

use strict;
use warnings;

my %data;
my $year = (localtime (time))[5] + 1900;

if (@ARGV &&
    ! -f $ARGV[0])
{
  $year = shift @ARGV;
}

while (my $line = <>)
{
  next if $line !~ /\/${year}/;
  next if $line !~ /"GET /;
  next if $line !~ /" 200 /;

  chomp $line;
  $line =~ s/^.+GET //;
  $line =~ s/ HTTP.+$//;
  $line =~ s/\?.+$//;

  $data{$line}++;
}

print $year, "\n\n";
printf ("%6d %s\n", $data{$_}, $_) for sort {$data{$b} <=> $data{$a}}keys %data;
exit 0;

