#!/bin/bash

TOTAL=0
MONTH_START=2016-11-01
MONTH_END=2016-12-01

for REPO in ~/gbf/*.git
do
  if [[ -d $REPO ]]
  then
    cd $REPO
    COMMITS=$(git log --pretty=oneline --date=short --since="${MONTH_START} 0:00:00" --until="${MONTH_END} 0:00:00" | wc -l)

    if [[ $COMMITS -gt 0 ]]
    then
      printf "%-22s %4d\n" $(basename $REPO) $COMMITS

      eval "git log --format='%an %ae' --date=short --since=\"${MONTH_START} 0:00:00\" --until=\"${MONTH_END} 0:00:00\"" | while read line
      do
        if [[ ! $line =~ 'Beckingham' && ! $line =~ 'Hernandez' && ! $line =~ 'Deimeke' ]]
        then
          echo "  $line"
        fi
      done
    fi

    TOTAL=$(expr $TOTAL + $COMMITS)
  fi
done

echo   '                       ----'
printf "TOTAL                  %4d\n" $TOTAL

