#!/bin/bash

MONTH_START=2017-02-01
MONTH_END=2017-03-01
IFS=

for REPO in ~/gbf/*.git
do
  if [[ -d $REPO ]]
  then
    echo $REPO
    cd $REPO

    eval "git log --format='%H %an %ae %ai' --date=short --since=\"${MONTH_START} 0:00:00\" --until=\"${MONTH_END} 0:00:00\"" | while read line
    do
      if [[ ! $line =~ 'Beckingham' ]]
      then
        echo "  $line"
      fi
    done
  fi
done

